---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sgsR - structurally guided sampling using ALS metrics

<!-- badges: start -->
<!-- badges: end -->

`sgsR` is designed to implement structurally guided sampling approaches for enhanced forest inventories. The package was designed to function using rasterized airborne laser scanning (ALS; Lidar) metrics to allow for stratification of forested areas based on structure.

## Installation

You can install the released version of sgsR from [Github](https://github.com/tgoodbody/sgsR) with:

``` r
install.packages("devtools")
devtools::install_github("https://github.com/tgoodbody/sgsR", build_vignettes = TRUE)
library(sgsR)
```

## Implementation {.unnumbered}

* Describe package fundamentals - `vignette("fundamentals")`

* Overview of sampling algorithms - `vignette("sampling")`

* Overview of stratification algorithms - `vignette("stratification")`

* Overview of calculate algorithms - `vignette("calculating")`

## Funding {.unnumbered}
Development of sgsR was made possible thanks to the financial support of the Canadian Wood Fibre Centre.

